name: PR Workflow - Default Merge Ref

on:
  pull_request:

run-name: Build and Deploy Feature Branch ${{ github.ref_name }}

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR run showing merge ref"
