name: PR Workflow - Clean Branch Name

on:
  pull_request:

run-name: Build and Deploy – Feature Branch ${{ github.head_ref }} (PR #${{ github.event.pull_request.number }})
 


jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR run showing feature branch"
